apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: scdf-dev
  labels:
    app: postgres
data:
  POSTGRES_DB: scdf_db
  POSTGRES_USER: scdf_admin
  POSTGRES_PASSWORD: B2U1vS8ry^h8wNb@M@NB

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  namespace: scdf-dev
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/volume"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: scdf-dev
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: scdf-dev
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14.5
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: scdf-db-volume
      volumes:
        - name: scdf-db-volume
          persistentVolumeClaim:
            claimName: postgres-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: scdf-dev
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres
