apiVersion: v1
kind: ConfigMap
metadata:
  name: scdf-server
  namespace: scdf-dev
  labels:
    app: scdf-server
data:
  application.yaml: |-
    spring:
      cloud:
        dataflow:
          applicationProperties:
            stream:
              management:
                metrics:
                  export:
                    prometheus:
                      enabled: true
                      rsocket:
                        enabled: true
                        host: prometheus-proxy
                        port: 7001
            task:
              management:
                metrics:
                  export:
                    prometheus:
                      enabled: true
                      rsocket:
                        enabled: true
                        host: prometheus-proxy
                        port: 7001
          grafana-info:
            url: 'https://grafana:3000'
          task:
            platform:
              kubernetes:
                accounts:
                  default:
                    limits:
                      memory: 1024Mi
      datasource:
        url: jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT}/mysql
        username: root
        password: ${mysql-root-password}
        driverClassName: org.mariadb.jdbc.Driver
        testOnBorrow: true
        validationQuery: "SELECT 1"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: scdf-server
  namespace: scdf-dev
  labels:
    app: scdf-server
spec:
  selector:
    matchLabels:
      app: scdf-server
  replicas: 1
  template:
    metadata:
      labels:
        app: scdf-server
    spec:
      containers:
        - name: scdf-server
          image: springcloud/spring-cloud-dataflow-server:2.9.5
          imagePullPolicy: Always
          volumeMounts:
            - name: database
              mountPath: /etc/secrets/database
              readOnly: true
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /management/health
              port: 80
            initialDelaySeconds: 45
          readinessProbe:
            httpGet:
              path: /management/info
              port: 80
            initialDelaySeconds: 45
          resources:
            limits:
              cpu: 1.0
              memory: 2048Mi
            requests:
              cpu: 0.5
              memory: 1024Mi
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
            - name: SERVER_PORT
              value: '80'
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: 'false'
            - name: SPRING_CLOUD_DATAFLOW_FEATURES_ANALYTICS_ENABLED
              value: 'true'
            - name: SPRING_CLOUD_DATAFLOW_FEATURES_SCHEDULES_ENABLED
              value: 'true'
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLE_API
              value: 'true'
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_PATHS
              value: /etc/secrets
            - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAME
              value: scdf-server
            - name: SPRING_CLOUD_DATAFLOW_SERVER_URI
              value: 'http://${SCDF_SERVER_SERVICE_HOST}:${SCDF_SERVER_SERVICE_PORT}'
            - name: SPRING_CLOUD_SKIPPER_CLIENT_SERVER_URI
              value: 'http://${SKIPPER_SERVICE_HOST}:${SKIPPER_SERVICE_PORT}/api'
            - name: SPRING_APPLICATION_JSON
              value: "{ \"maven\": { \"local-repository\": null, \"remote-repositories\": { \"repo1\": { \"url\": \"https://repo.spring.io/libs-snapshot\"} } } }"
      initContainers:
        - name: init-mysql-wait
          image: busybox
          command: ['sh', '-c', 'until nc -w3 -z mysql 3306; do echo waiting for mysql; sleep 3; done;']
      serviceAccountName: scdf-sa
      volumes:
        - name: database
          secret:
            secretName: mysql

---

kind: Service
apiVersion: v1
metadata:
  name: scdf-server
  namespace: scdf-dev
  labels:
    app: scdf-server
    spring-deployment-id: scdf
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: scdf-server
  selector:
    app: scdf-server
